
FROM halohub/halo:2.0.0
ENV HALO_EXTERNAL_URL http://localhost:8090/
ENV HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD P@77w0rd
ENV SPRING_R2DBC_URL postgres://halo:EBTr9CN5LIbjTHbLVpMA4JggVfGHMXak@dpg-ce7ijaqrrk049r5v2hq0-a/halo_swh5
ENV SPRING_R2DBC_USERNAME halo
ENV SPRING_R2DBC_PASSWORD EBTr9CN5LIbjTHbLVpMA4JggVfGHMXak
ENV SPRING_SQL_INIT_PLATFORM postgresql
EXPOSE 8090
